### ISSUE TITLE
When user clicked on "features" or "data" it wasn't clear how to get back to map

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#558]
"I figured out I had to click on the PFF header, but maybe if there was a small 'return to selection view' or 'return to map' button/icon on that page it would help"

**Comment by allthesignals** [comment]
I think this was addressed with this:

<img width="669" alt="Screen Shot 2020-03-04 at 6 54 22 PM" src="https://user-images.githubusercontent.com/5004319/75938615-32c21500-5e56-11ea-97b1-88300df112d4.png">

**Comment by EricaMaurer** [comment]
this issue was from any of the other pages-- about, tutorial, data, features. 
still an issue.

**Comment by allthesignals** [comment]
Oooh. My bad. Thanks for clarification! Very easy win.
